name: SPCOutlook
options:
  bundleIdPrefix: com.uridarom
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true

targets:
  SPCOutlook:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: SPCOutlook
    settings:
      base:
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1"
        PRODUCT_BUNDLE_IDENTIFIER: com.uridarom.SPCOutlook
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
    info:
      path: SPCOutlook/Info.plist
      properties:
        CFBundleDisplayName: SPC Outlook
        UIApplicationSceneManifest:
          UIApplicationIsSceneConfigurationRequired: true
          UISceneConfigurations: {}
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIUserInterfaceStyle: Dark

  SPCOutlookTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: SPCOutlookTests
    dependencies:
      - target: SPCOutlook
    settings:
      base:
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: YES
